// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewCariDefteri.Models;

namespace NewCariDefteri.Migrations
{
    [DbContext(typeof(caridefteriContext))]
    partial class caridefteriContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NewCariDefteri.Models.Info", b =>
                {
                    b.Property<int>("InfoId")
                        .HasColumnName("info_Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("PersonId")
                        .HasColumnName("Person_Id")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("InfoId");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasName("UQ__Info__7EABD0AA1BC1B8B9")
                        .HasFilter("[Person_Id] IS NOT NULL");

                    b.ToTable("Info");
                });

            modelBuilder.Entity("NewCariDefteri.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Person_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Soyad")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("UserId")
                        .HasColumnName("User_Id")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasName("UQ__Person__206D91718610BC49")
                        .HasFilter("[User_Id] IS NOT NULL");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("NewCariDefteri.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("User_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Parola")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("UserId")
                        .HasName("PK__Users__206D9190E522EAFC");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewCariDefteri.Models.Info", b =>
                {
                    b.HasOne("NewCariDefteri.Models.Person", "Person")
                        .WithOne("Info")
                        .HasForeignKey("NewCariDefteri.Models.Info", "PersonId")
                        .HasConstraintName("FK__Info__Person_Id__47DBAE45");
                });

            modelBuilder.Entity("NewCariDefteri.Models.Person", b =>
                {
                    b.HasOne("NewCariDefteri.Models.Users", "User")
                        .WithOne("Person")
                        .HasForeignKey("NewCariDefteri.Models.Person", "UserId")
                        .HasConstraintName("FK__Person__User_Id__440B1D61");
                });
#pragma warning restore 612, 618
        }
    }
}
